import turtle

turtle.penup()
turtle.goto(-50, 50)
turtle.pendown()
turtle.fd(100)
turtle.right(90)
turtle.fd(100)
turtle.right(90)
turtle.fd(100)
turtle.right(90)
turtle.fd(100)
turtle.right(90)
turtle.penup()
turtle.goto(-50, 0)
turtle.pendown()
turtle.forward(100)
turtle.penup()
turtle.goto(0, -50)
turtle.pendown()
turtle.left(90)
turtle.forward(50)
turtle.penup()
turtle.goto(0, 50)
turtle.right(180)
turtle.pendown()
turtle.forward(50)

turtle.done()
