import turtle

turtle.circle(300)
turtle.penup()
turtle.goto(0, 300)
turtle.pendown()
turtle.goto(275, 300)
turtle.penup()
turtle.goto(0, 300)
turtle.pendown()
turtle.goto(0, 550)
turtle.penup()
turtle.goto(0, 300)
turtle.pendown()
turtle.goto(-225, 300)
turtle.penup()
turtle.goto(0, 580)
turtle.pendown()
turtle.write("12")
turtle.penup()
turtle.goto(290, 300)
turtle.pendown()
turtle.write("3")
turtle.penup()
turtle.goto(0, 20)
turtle.pendown()
turtle.write("6")
turtle.penup()
turtle.goto(-280, 300)
turtle.pendown()
turtle.write("9")
turtle.penup()
turtle.goto(0, -20)
turtle.pendown()
turtle.write("9:15:00")

turtle.done()